x-common: &common-setup
  network_mode: host
  privileged: true
  volumes:
    - ${HOME}/.Xauthority:/home/fabian/.Xauthority:rw
    - .:/home/fabian/ros2_ws/src:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev/dri:/dev/dri:rw
    - /run/user/1000/pulse:/run/user/1000/pulse
  environment:
    - DISPLAY
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/home/fabian/.Xauthority
  working_dir: /home/fabian/ros2_ws

services:
  terminal:
    <<: *common-setup
    image: fabook/iros:lidar-lab-v0.0.1
    stdin_open: true
    tty: true
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/snd:/dev/snd"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    group_add:
      - "video"
      - "44"
    command: [
      "/bin/bash","-lc","
      exec bash"
      ]
